INSERT INTO `fusion`.`fusion_sys_menu_conf`( `deleted`, `raw_add_time`, `raw_creator`, `raw_modifier`, `raw_update_time`, `raw_version`, `common`, `menu_code`, `menu_name`, `menu_parent_code`, `menu_parent_name`, `menu_url`, `menu_ordby`, `menu_state`) VALUES (0, '2018-06-14 11:45:25', 'liaoguowei1', , NULL, 'info', '人才信息', '', '', '', NULL, NULL);
INSERT INTO `fusion`.`fusion_sys_menu_conf`(`deleted`, `raw_add_time`, `raw_creator`, `raw_modifier`, `raw_update_time`, `raw_version`, `common`, `menu_code`, `menu_name`, `menu_parent_code`, `menu_parent_name`, `menu_url`, `menu_ordby`, `menu_state`) VALUES ( 0, '2018-06-14 11:45:42', 'liaoguowei1', , NULL, 'info-person', '个人信息表', 'info', '人才信息', '', NULL, NULL);
INSERT INTO `fusion`.`fusion_sys_menu_conf`(`deleted`, `raw_add_time`, `raw_creator`, `raw_modifier`, `raw_update_time`, `raw_version`, `common`, `menu_code`, `menu_name`, `menu_parent_code`, `menu_parent_name`, `menu_url`, `menu_ordby`, `menu_state`) VALUES (0, '2018-06-14 11:46:15', 'liaoguowei1', , NULL, 0, 'talents', '环境与生态人才库', '', '', '', NULL, NULL);
INSERT INTO `fusion`.`fusion_sys_menu_conf`(`deleted`, `raw_add_time`, `raw_creator`, `raw_modifier`, `raw_update_time`, `raw_version`, `common`, `menu_code`, `menu_name`, `menu_parent_code`, `menu_parent_name`, `menu_url`, `menu_ordby`, `menu_state`) VALUES (0, '2018-06-14 11:46:39', 'liaoguowei1', , NULL, 0, 'talents-apply', '人才库申报表', 'talents', '环境与生态人才库', '', NULL, NULL);
INSERT INTO `fusion`.`fusion_sys_menu_conf`(`deleted`, `raw_add_time`, `raw_creator`, `raw_modifier`, `raw_update_time`, `raw_version`, `common`, `menu_code`, `menu_name`, `menu_parent_code`, `menu_parent_name`, `menu_url`, `menu_ordby`, `menu_state`) VALUES (0, '2018-06-14 11:47:01', 'liaoguowei1', 'liaoguowei1', NULL, 3, 0, 'talents-tList', '人才库表', 'talents', '环境与生态人才库', '', NULL, NULL);
INSERT INTO `fusion`.`fusion_sys_menu_conf`(`deleted`, `raw_add_time`, `raw_creator`, `raw_modifier`, `raw_update_time`, `raw_version`, `common`, `menu_code`, `menu_name`, `menu_parent_code`, `menu_parent_name`, `menu_url`, `menu_ordby`, `menu_state`) VALUES (0, '2018-06-14 11:47:53', 'liaoguowei1', , NULL, 0, 'expert', '专家库查询', '', '', '', NULL, NULL);
INSERT INTO `fusion`.`fusion_sys_menu_conf`(`deleted`, `raw_add_time`, `raw_creator`, `raw_modifier`, `raw_update_time`, `raw_version`, `common`, `menu_code`, `menu_name`, `menu_parent_code`, `menu_parent_name`, `menu_url`, `menu_ordby`, `menu_state`) VALUES (0, '2018-06-14 11:48:22', 'liaoguowei1', , NULL, 0, 'expert-eList', '专家表查询', 'expert', '专家库查询', '', NULL, NULL);
INSERT INTO `fusion`.`fusion_sys_menu_conf`(`deleted`, `raw_add_time`, `raw_creator`, `raw_modifier`, `raw_update_time`, `raw_version`, `common`, `menu_code`, `menu_name`, `menu_parent_code`, `menu_parent_name`, `menu_url`, `menu_ordby`, `menu_state`) VALUES (0, '2018-06-14 11:48:48', 'liaoguowei1', , NULL, 0, 'set', '系统设置', '', '', '', NULL, NULL);
INSERT INTO `fusion`.`fusion_sys_menu_conf`(`deleted`, `raw_add_time`, `raw_creator`, `raw_modifier`, `raw_update_time`, `raw_version`, `common`, `menu_code`, `menu_name`, `menu_parent_code`, `menu_parent_name`, `menu_url`, `menu_ordby`, `menu_state`) VALUES (0, '2018-06-14 11:49:10', 'liaoguowei1', , NULL, 0, 'set-user', '用户管理', 'set', '系统设置', '', NULL, NULL);
INSERT INTO `fusion`.`fusion_sys_menu_conf`(`deleted`, `raw_add_time`, `raw_creator`, `raw_modifier`, `raw_update_time`, `raw_version`, `common`, `menu_code`, `menu_name`, `menu_parent_code`, `menu_parent_name`, `menu_url`, `menu_ordby`, `menu_state`) VALUES (0, '2018-06-14 11:49:31', 'liaoguowei1', , NULL, 0, 'set-menu', '菜单管理', 'set', '系统设置', '', NULL, NULL);
INSERT INTO `fusion`.`fusion_sys_menu_conf`(`deleted`, `raw_add_time`, `raw_creator`, `raw_modifier`, `raw_update_time`, `raw_version`, `common`, `menu_code`, `menu_name`, `menu_parent_code`, `menu_parent_name`, `menu_url`, `menu_ordby`, `menu_state`) VALUES (0, '2018-06-14 11:49:48', 'liaoguowei1', , NULL, 0, 'set-role', '角色管理', 'set', '系统设置', '', NULL, NULL);


/*初始化属性值*/
INSERT INTO `sampling`.`sampling_table_property`(deleted`, `raw_add_time`, `raw_creator`, `raw_modifier`, `raw_update_time`, property_category_code`, `property_category_name`, `property_code`, `property_html`, `property_label_type`, `property_name`) VALUES (0, '2018-07-11 20:58:57', NULL, NULL, NULL, '001', '基本属性', 'businessCode', '<span style=\"font-weight:bold;color:#287bd3e8\" aliasCode=\"businessCode\" >业务编号</span>', 'span', '业务编号');
INSERT INTO `sampling`.`sampling_table_property`(deleted`, `raw_add_time`, `raw_creator`, `raw_modifier`, `raw_update_time`, property_category_code`, `property_category_name`, `property_code`, `property_html`, `property_label_type`, `property_name`) VALUES (0, '2018-07-11 20:59:45', NULL, NULL, NULL, '001', '基本属性', 'operatorCode', '<span style=\"font-weight:bold;color:#287bd3e8\" aliasCode=\"operatorCode\" >操作人编号</span>', 'span', '操作人编号');
INSERT INTO `sampling`.`sampling_table_property`(deleted`, `raw_add_time`, `raw_creator`, `raw_modifier`, `raw_update_time`, property_category_code`, `property_category_name`, `property_code`, `property_html`, `property_label_type`, `property_name`) VALUES (0, '2018-07-11 21:00:12', NULL, NULL, NULL, '001', '基本属性', 'operatorName', '<span style=\"font-weight:bold;color:#287bd3e8\" aliasCode=\"operatorName\" >操作人名称</span>', 'span', '操作人名称');
INSERT INTO `sampling`.`sampling_table_property`(deleted`, `raw_add_time`, `raw_creator`, `raw_modifier`, `raw_update_time`, property_category_code`, `property_category_name`, `property_code`, `property_html`, `property_label_type`, `property_name`) VALUES (0, '2018-07-11 21:00:41', NULL, NULL, NULL, '001', '基本属性', 'operatorDepartmentCode', '<span style=\"font-weight:bold;color:#287bd3e8\" aliasCode=\"operatorDepartmentCode\" >操作人所属科室编号</span>', 'span', '操作人所属科室编号');
INSERT INTO `sampling`.`sampling_table_property`(deleted`, `raw_add_time`, `raw_creator`, `raw_modifier`, `raw_update_time`, property_category_code`, `property_category_name`, `property_code`, `property_html`, `property_label_type`, `property_name`) VALUES (0, '2018-07-11 21:01:37', NULL, NULL, NULL, '001', '基本属性', 'operatorDepartmentName', '<span style=\"font-weight:bold;color:#287bd3e8\" aliasCode=\"operatorDepartmentName\" >操作人所属科室名称</span>', 'span', '操作人所属科室名称');
INSERT INTO `sampling`.`sampling_table_property`(deleted`, `raw_add_time`, `raw_creator`, `raw_modifier`, `raw_update_time`, property_category_code`, `property_category_name`, `property_code`, `property_html`, `property_label_type`, `property_name`) VALUES (0, '2018-07-11 21:02:19', NULL, NULL, NULL, '001', '基本属性', 'clientName', '<span style=\"font-weight:bold;color:#287bd3e8\" aliasCode=\"clientName\" >委托单位</span>', 'span', '委托单位');
INSERT INTO `sampling`.`sampling_table_property`(deleted`, `raw_add_time`, `raw_creator`, `raw_modifier`, `raw_update_time`, property_category_code`, `property_category_name`, `property_code`, `property_html`, `property_label_type`, `property_name`) VALUES (0, '2018-07-11 21:02:40', NULL, NULL, NULL, '001', '基本属性', 'clientAddress', '<span style=\"font-weight:bold;color:#287bd3e8\" aliasCode=\"clientAddress\" >委托单位地址</span>', 'span', '委托单位地址');
INSERT INTO `sampling`.`sampling_table_property`(deleted`, `raw_add_time`, `raw_creator`, `raw_modifier`, `raw_update_time`, property_category_code`, `property_category_name`, `property_code`, `property_html`, `property_label_type`, `property_name`) VALUES (0, '2018-07-11 21:03:07', NULL, NULL, NULL, '001', '基本属性', 'clientContactPerson', '<span style=\"font-weight:bold;color:#287bd3e8\" aliasCode=\"clientContactPerson\" >委托单位联系人</span>', 'span', '委托单位联系人');
INSERT INTO `sampling`.`sampling_table_property`(deleted`, `raw_add_time`, `raw_creator`, `raw_modifier`, `raw_update_time`, property_category_code`, `property_category_name`, `property_code`, `property_html`, `property_label_type`, `property_name`) VALUES (0, '2018-07-11 21:03:35', NULL, NULL, NULL, '001', '基本属性', 'clientContactPhone', '<span style=\"font-weight:bold;color:#287bd3e8\" aliasCode=\"clientContactPhone\" >委托单位联系人电话</span>', 'span', '委托单位联系人电话');
INSERT INTO `sampling`.`sampling_table_property`(deleted`, `raw_add_time`, `raw_creator`, `raw_modifier`, `raw_update_time`, property_category_code`, `property_category_name`, `property_code`, `property_html`, `property_label_type`, `property_name`) VALUES (0, '2018-07-11 21:04:18', NULL, NULL, NULL, '001', '基本属性', 'detectiveCode', '<span style=\"font-weight:bold;color:#287bd3e8\" aliasCode=\"detectiveCode\" >检测项编号</span>', 'span', '检测项编号');
INSERT INTO `sampling`.`sampling_table_property`(deleted`, `raw_add_time`, `raw_creator`, `raw_modifier`, `raw_update_time`, property_category_code`, `property_category_name`, `property_code`, `property_html`, `property_label_type`, `property_name`) VALUES (0, '2018-07-11 21:04:54', NULL, NULL, NULL, '001', '基本属性', 'detectiveName', '<span style=\"font-weight:bold;color:#287bd3e8\" aliasCode=\"detectiveName\" >检测项名称</span>', 'span', '检测项名称');
INSERT INTO `sampling`.`sampling_table_property`(deleted`, `raw_add_time`, `raw_creator`, `raw_modifier`, `raw_update_time`, property_category_code`, `property_category_name`, `property_code`, `property_html`, `property_label_type`, `property_name`) VALUES (0, '2018-07-11 21:05:17', NULL, NULL, NULL, '001', '基本属性', 'methodCode', '<span style=\"font-weight:bold;color:#287bd3e8\" aliasCode=\"methodCode\" >方法编号</span>', 'span', '方法编号');
INSERT INTO `sampling`.`sampling_table_property`(deleted`, `raw_add_time`, `raw_creator`, `raw_modifier`, `raw_update_time`, property_category_code`, `property_category_name`, `property_code`, `property_html`, `property_label_type`, `property_name`) VALUES (0, '2018-07-11 21:05:40', NULL, NULL, NULL, '001', '基本属性', 'methodName', '<span style=\"font-weight:bold;color:#287bd3e8\" aliasCode=\"methodName\" >方法名称</span>', 'span', '方法名称');
INSERT INTO `sampling`.`sampling_table_property`(deleted`, `raw_add_time`, `raw_creator`, `raw_modifier`, `raw_update_time`, property_category_code`, `property_category_name`, `property_code`, `property_html`, `property_label_type`, `property_name`) VALUES (0, '2018-07-11 21:06:18', NULL, NULL, NULL, '001', '基本属性', 'inspectorName', '<span style=\"font-weight:bold;color:#287bd3e8\" aliasCode=\"inspectorName\" >检测人名称</span>', 'span', '检测人名称');
INSERT INTO `sampling`.`sampling_table_property`(deleted`, `raw_add_time`, `raw_creator`, `raw_modifier`, `raw_update_time`, property_category_code`, `property_category_name`, `property_code`, `property_html`, `property_label_type`, `property_name`) VALUES (0, '2018-07-11 21:06:43', NULL, NULL, NULL, '001', '基本属性', 'inspectorCode', '<span style=\"font-weight:bold;color:#287bd3e8\" aliasCode=\"inspectorCode\" >检测人编码</span>', 'span', '检测人编码');
INSERT INTO `sampling`.`sampling_table_property`(deleted`, `raw_add_time`, `raw_creator`, `raw_modifier`, `raw_update_time`, property_category_code`, `property_category_name`, `property_code`, `property_html`, `property_label_type`, `property_name`) VALUES (0, '2018-07-11 21:07:24', NULL, NULL, NULL, '001', '基本属性', 'departmentCode', '<span style=\"font-weight:bold;color:#287bd3e8\" aliasCode=\"departmentCode\" >科室编码</span>', 'span', '科室编码');
INSERT INTO `sampling`.`sampling_table_property`(deleted`, `raw_add_time`, `raw_creator`, `raw_modifier`, `raw_update_time`, property_category_code`, `property_category_name`, `property_code`, `property_html`, `property_label_type`, `property_name`) VALUES (0, '2018-07-11 21:07:49', NULL, NULL, NULL, '001', '基本属性', 'departmentName', '<span style=\"font-weight:bold;color:#287bd3e8\" aliasCode=\"departmentName\" >科室名称</span>', 'span', '科室名称');
INSERT INTO `sampling`.`sampling_table_property`(deleted`, `raw_add_time`, `raw_creator`, `raw_modifier`, `raw_update_time`, property_category_code`, `property_category_name`, `property_code`, `property_html`, `property_label_type`, `property_name`) VALUES (0, '2018-07-11 21:11:27', NULL, NULL, NULL, '001', '基本属性', 'samplingCode', ' <span style=\"font-weight:bold;color:#287bd3e8\" aliasCode=\"samplingCode\" >样品编号</span>', 'span', '样品编号');
INSERT INTO `sampling`.`sampling_table_property`(deleted`, `raw_add_time`, `raw_creator`, `raw_modifier`, `raw_update_time`, property_category_code`, `property_category_name`, `property_code`, `property_html`, `property_label_type`, `property_name`) VALUES (0, '2018-07-11 21:12:47', NULL, NULL, NULL, '001', '基本属性', 'samplingName', '<span style=\"font-weight:bold;color:#287bd3e8\" aliasCode=\"samplingName\" >样品名称</span>', 'span', '样品名称');
INSERT INTO `sampling`.`sampling_table_property`(deleted`, `raw_add_time`, `raw_creator`, `raw_modifier`, `raw_update_time`, property_category_code`, `property_category_name`, `property_code`, `property_html`, `property_label_type`, `property_name`) VALUES (0, '2018-07-11 21:13:10', NULL, NULL, NULL, '001', '基本属性', 'samplingProduceType', '<span style=\"font-weight:bold;color:#287bd3e8\" aliasCode=\"samplingProduceType\" >样品类别</span>', 'span', '样品类别');
INSERT INTO `sampling`.`sampling_table_property`(deleted`, `raw_add_time`, `raw_creator`, `raw_modifier`, `raw_update_time`, property_category_code`, `property_category_name`, `property_code`, `property_html`, `property_label_type`, `property_name`) VALUES (0, '2018-07-11 21:13:41', NULL, NULL, NULL, '001', '基本属性', 'dataUnit', '<span style=\"font-weight:bold;color:#287bd3e8\" aliasCode=\"dataUnit\" >样品计量单位</span>', 'span', '样品计量单位');
INSERT INTO `sampling`.`sampling_table_property`(deleted`, `raw_add_time`, `raw_creator`, `raw_modifier`, `raw_update_time`, property_category_code`, `property_category_name`, `property_code`, `property_html`, `property_label_type`, `property_name`) VALUES (0, '2018-07-11 21:14:04', NULL, NULL, NULL, '001', '基本属性', 'samplingPositionCode', '<span style=\"font-weight:bold;color:#287bd3e8\" aliasCode=\"samplingPositionCode\" >采样点编号</span>', 'span', '采样点编号');
INSERT INTO `sampling`.`sampling_table_property`(deleted`, `raw_add_time`, `raw_creator`, `raw_modifier`, `raw_update_time`, property_category_code`, `property_category_name`, `property_code`, `property_html`, `property_label_type`, `property_name`) VALUES (0, '2018-07-11 21:14:25', NULL, NULL, NULL, '001', '基本属性', 'samplingPositionName', '<span style=\"font-weight:bold;color:#287bd3e8\" aliasCode=\"samplingPositionName\" >采样点名称</span>', 'span', '采样点名称');
INSERT INTO `sampling`.`sampling_table_property`(deleted`, `raw_add_time`, `raw_creator`, `raw_modifier`, `raw_update_time`, property_category_code`, `property_category_name`, `property_code`, `property_html`, `property_label_type`, `property_name`) VALUES (0, '2018-07-11 21:14:53', NULL, NULL, NULL, '001', '基本属性', 'samplingStatus', '<span style=\"font-weight:bold;color:#287bd3e8\" aliasCode=\"samplingStatus\" >采样状态</span>', 'span', '采样状态');
INSERT INTO `sampling`.`sampling_table_property`(deleted`, `raw_add_time`, `raw_creator`, `raw_modifier`, `raw_update_time`, property_category_code`, `property_category_name`, `property_code`, `property_html`, `property_label_type`, `property_name`) VALUES (0, '2018-07-11 21:15:17', NULL, NULL, NULL, '001', '基本属性', 'remark', '<span style=\"font-weight:bold;color:#287bd3e8\" aliasCode=\"remark\" >采样备注</span>', 'span', '采样备注');

